version: '3'

services:

  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/.influxdbv2
    ports:
      - "8083:8083"
      - "8086:8086"
volumes:
  influxdbv2:
