#!/usr/bin/perl -w

# -------------------------------------------------------------------------
# Bernese GPS Software Version 5.0
# -------------------------------------------------------------------------
#
# Script:     RBPE
#
# Purpose:    Run a BPE Script that resides in ${BPE} Directory
#
# Author:     L. Mervart
#
# Created:    12-FEB-2002
#
# Changes:
#
# Copyright:  Astronomical Institute
#              University of Berne
#                  Switzerland
# -------------------------------------------------------------------------

use strict;
use lib "$ENV{BPE}";
use RUNBPE;

RUNBPE::RBPE(@ARGV);

