      MODULE s_DATTIM
      CONTAINS

C*
      SUBROUTINE DATTIM(DATSTR,TIMSTR)
CC
CC NAME       :  DATTIM
CC
CC PURPOSE    :  GET SYSTEM DATE AND TIME (EX.: 12-JAN-87 15:45)
CC
CC PARAMETERS :
CC        OUT :  DATSTR : ACTUAL SYSTEM DATE                  CH*9
CC               TIMSTR : ACTUAL SYSTEM TIME                  CH*5
CC
CC REMARKS    :
CC
CC AUTHOR     :  L. MERVART
CC
CC VERSION    :  3.6  (SEP 95)
CC
CC CREATED    :  11-SEP-95
CC
CC CHANGES    :  23-JUN-05 : MM: IMPLICIT NONE
CC
CC COPYRIGHT  :  ASTRONOMICAL INSTITUTE
CC      1995     UNIVERSITY OF BERN
CC               SWITZERLAND
CC
C*
      USE s_clocks
      IMPLICIT NONE
CCC       IMPLICIT REAL*8 (A-H,O-Z)
CCC       IMPLICIT INTEGER*4 (I-N)
C
      CHARACTER   DATSTR*9,TIMSTR*5,MONTH(12)*3
      INTEGER*4   MM(8)
C
      DATA MONTH/'JAN','FEB','MAR','APR','MAY','JUN',
     1           'JUL','AUG','SEP','OCT','NOV','DEC'/
C
      CALL CLOCKS(MM)
C
      WRITE(DATSTR,1)MM(3),MONTH(MM(2)),MOD(MM(1),100)
1     FORMAT(I2.2,'-',A3,'-',I2.2)
C
      WRITE(TIMSTR,2)MM(5),MM(6)
2     FORMAT(I2.2,':',I2.2)
C
      RETURN
      END SUBROUTINE

      END MODULE
