      MODULE f_fakult
      CONTAINS

C*
      FUNCTION FAKULT(N)
CC
CC NAME       :  FAKULT (REAL*8 FUNCTION)
CC
CC    XXX = FAKULT(N)
CC
CC PURPOSE    :  COMPUTES THE FACTORIAL OF N
CC
CC PARAMETERS :
CC         IN :  N      : ARGUMENT OF FACTORIAL               I*4
CC        OUT :  FAKULT : FACTORIAL OF N                      R*8
CC
CC REMARKS    :  ---
CC
CC AUTHOR     :  G.BEUTLER
CC
CC VERSION    :  3.4  (JAN 93)
CC
CC CREATED    :  87/12/10 18:57
CC
CC CHANGES    :  23-JUN-05 : MM: IMPLICIT NONE AND DECLARATIONS ADDED
CC
CC COPYRIGHT  :  ASTRONOMICAL INSTITUTE
CC      1987     UNIVERSITY OF BERN
CC               SWITZERLAND
CC
C*
      IMPLICIT NONE
C
C DECLARATIONS INSTEAD OF IMPLICIT
C --------------------------------
      INTEGER*4 I, N
C
        REAL*8 FAKULT
        FAKULT=1.D0
        IF(N.LE.1) RETURN
        DO 10 I=2,N
10      FAKULT=FAKULT*I
        RETURN
        END FUNCTION

      END MODULE
