      MODULE f_lengt0
      CONTAINS

C*
        FUNCTION LENGT0(STRING)
CC
CC NAME       :  LENGTH
CC
CC PURPOSE    : DETERMINE LENGTH OF A GIVEN STRING
CC              (TRAILING BLANKS OR ASCII NUL EXCLUDED)
CC
CC PARAMETERS :
CC         IN :  STRING: GIVEN STRING                             CH*(*)
CC        OUT :  LENGTH: LENGTH OF STRING                          I*4
CC
CC REMARKS     :
CC
CC RESTRICTION : NONE
CC
CC AUTHOR      : W. GURTNER
CC               ASTRONOMICAL INSTITUTE, UNIVERSITY OF BERN
CC               SWITZERLAND
CC
CC CREATED     : 01-JUN-87
CC
CC CHANGES     : 23-JUN-05: MM: IMPLICIT NONE AND DECLARATIONS
CC
C*
      IMPLICIT NONE
C
C DECLARATIONS INSTEAD OF IMPLICIT
C --------------------------------
      INTEGER*4 I     , LENGT0, LENSTR
C
        CHARACTER STRING*(*)
        CHARACTER NUL
        NUL=CHAR(0)
C
        LENSTR=LEN(STRING)
        DO 10 I=LENSTR,1,-1
          IF(STRING(I:I).NE.' '.AND.STRING(I:I).NE.NUL) GOTO 20
10      CONTINUE
20      LENGT0=I
        RETURN
        END FUNCTION

      END MODULE
