      MODULE s_PROMP1
      CONTAINS

C*
      SUBROUTINE PROMP1(NLINE,STRING)
CC
CC NAME       :  PROMP1
CC
CC PURPOSE    :  DISPLAY STRING(S) TO PROMP1 FOR INPUT
CC               (I.E. NO CARRIAGE RETURN AFTER PROMP1)
CC
CC PARAMETERS :
CC         IN :  NLINE  : NUMBER OF LINES TO BE DISPLAYED        I*4
CC               STRING : STRING(S) TO BE DISPLAYED          CH(*)*(*)
CC
CC REMARKS    :  THIS ROUTINE IS COMPILER-DEPENDENT, SINCE THERE IS
CC               NO STANDARD FOR CR-SUPPRESSION
CC               -->  HP9000/835 HP-UX,SunOS,ULTRIX VERSION  <--
CC               SunOS VERSION INCLUDED IN COMMENT LINES
CC
CC AUTHOR     :  W. GURTNER, H.FRIEDHOFF
CC
CC VERSION    :  3.1
CC
CC CREATED    :  31-DEC-90
CC
CC CHANGES    :  06-AUG-99 : JJ: ADD "C_LANG_Fxx"
CC               17-Feb-03 : LM: RENAMED FROM U_PROMP1, MYFLUSH REMOVED
CC               23-JUN-05 : MM: IMPLICIT NONE AND DECLARATIONS ADDED
CC               27-MAR-12 : RD: USE PROMP1 AS MODULE NOW
CC
CC COPYRIGHT  :  ASTRONOMICAL INSTITUTE
CC      1990     UNIVERSITY OF BERN
CC               SWITZERLAND
CC
C*
C
C  GLOBAL PARAMETERS
      USE f_lengt0
      IMPLICIT NONE
C
C DECLARATIONS INSTEAD OF IMPLICIT
C --------------------------------
      INTEGER*4 LS    , NLINE, I
C
      CHARACTER    STRING(*)*(*)
C
      DO 10 I=1,NLINE-1
        LS=LENGT0(STRING(I))
        WRITE(*,'(1X,A)') STRING(I)(1:LS)
10    CONTINUE
      LS=LENGT0(STRING(NLINE))
      WRITE(*,'(2A)',ADVANCE='NO') STRING(NLINE)(1:LS),' '
cccc      CALL MYFLUSH
C
      RETURN
      END SUBROUTINE

      END MODULE
