      MODULE s_SJUSTL
      CONTAINS

C*
        SUBROUTINE SJUSTL(STRING)
CC
CC NAME       :  SJUSTL
CC
CC PURPOSE    : LEFT JUSTIFY A CHARACTER STRING SO THAT
CC              FIRST NON-BLANK CHARACTER IS AT FIRST STRING
CC              POSITION.
CC
CC PARAMETERS :
CC     IN/OUT :  STRING: GIVEN STRING                             CH*(*)
CC
CC REMARKS     :
CC
CC RESTRICTION : NONE
CC
CC AUTHOR      : T. SCHILDKNECHT
CC               ASTRONOMICAL INSTITUTE, UNIVERSITY OF BERN
CC               SWITZERLAND
CC
CC CREATED     : 04-APR-91
CC
CC CHANGES     : 23-JUN-05 : MM: IMPLICIT NONE AND DECLARATIONS
CC
C*
      IMPLICIT NONE
C
C DECLARATIONS INSTEAD OF IMPLICIT
C --------------------------------
      INTEGER*4 I     , LENSTR
C
        CHARACTER STRING*(*)
C
        LENSTR=LEN(STRING)
        DO 10 I=1,LENSTR
          IF(STRING(I:I).NE.' ') GOTO 20
10      CONTINUE
        I=1
20      STRING(1:)=STRING(I:)
        RETURN
        END SUBROUTINE

      END MODULE
